tandem_iob_columns = [
    "Type",
    "EventID",
    "EventDateTime",
    "iob",
]

tandem_estimated_glu_columns = [
    "DeviceType",
    "SerialNumber",
    "Description",
    "EventDateTime",
    "bg",
    "VOID",
]

tandem_basal_rate_columns = [
    "Type",
    "EventDateTime",
    "br",
]

tandem_bolus_columns = [
    "Type",
    "BolusDescription",
    "bg_bolus",
    "iob_bolus",
    "BolusRequestID",
    "BolusCompletionID",
    "CompletionDateTime",
    "InsulinDelivered",
    "FoodDelivered",
    "CorrectionDelivered",
    "CompletionStatusID",
    "CompletionStatusDesc",
    "BolusIsComplete",
    "BolexCompletionID",
    "BolexSize",
    "BolexStartDateTime",
    "BolexCompletionDateTime",
    "BolexInsulinDelivered",
    "BolexIOB",
    "BolexCompletionStatusID",
    "BolexCompletionStatusDesc",
    "ExtendedBolusIsComplete",
    "EventDateTime",
    "RequestDateTime",
    "BolusType",
    "BolusRequestOptions",
    "StandardPercent",
    "Duration",
    "CarbSize",
    "UserOverride",
    "TargetBG",
    "CorrectionFactor",
    "FoodBolusSize",
    "CorrectionBolusSize",
    "ActualTotalBolusRequested",
    "IsQuickBolus",
    "EventHistoryReportEventDesc",
    "EventHistoryReportDetails",
    "NoteID",
    "IndexID",
    "Note",
]
